services:
  profile-service:
    container_name: profile-service-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://profile-postgres:5432/profile_db
    ports:
      - "8088:8080"
    depends_on:
      - profile-postgres

  profile-postgres:
    container_name: profile-db
    image: postgres:14-alpine
    ports:
      - "5448:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=profile_db