services:
  customer-service:
    container_name: customer-service-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://customer-postgres:5432/customer_db
    ports:
      - "8081:8080"
    depends_on:
      - customer-postgres

  customer-postgres:
    container_name: customer-db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=customer_db