services:
  deposit-service:
    container_name: deposit-service-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://deposit-postgres:5432/deposit_db
    ports:
      - "8082:8080"
    depends_on:
      - deposit-postgres

  deposit-postgres:
    container_name: deposit-db
    image: postgres:14-alpine
    ports:
      - "5442:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=deposit_db