services:
  payment-service:
    container_name: payment-service-app
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://payment-postgres:5432/payment_db
    ports:
      - "8082:8080"
    depends_on:
      - payment-postgres

  payment-postgres:
    container_name: payment-db
    image: postgres:14-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=payment_db