services:
  account-service:
    container_name: account-service-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://account-postgres:5432/account_db
    ports:
      - "8080:8080"
    depends_on:
      - account-postgres

  account-postgres:
    container_name: account-db
    image: postgres:14-alpine
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=account_db